### ISSUE TITLE
Duplicate DjVu added, with duplicated content

### ISSUE THREAD

**Issue by nemobis** [wikisource/ia-upload#5] opened 2015-03-12 17:59 UTC
[Miniwark noticed](https://commons.wikimedia.org/w/index.php?title=User_talk:Federico_Leva_%28BEIC%29&oldid=prev&diff=152917482) that https://commons.wikimedia.org/wiki/File:Sade_-_L%27oeuvre_du_marquis_de_Sade,_1909.djvu , uploaded by ia-upload, is an exact duplicate of https://commons.wikimedia.org/wiki/File:Sade_-_L%E2%80%99%C5%92uvre,_%C3%A9d._Apollinaire,_1909.djvu : both come from https://archive.org/details/loeuvredumarquis00sadeuoft

I've checked the IA item history and there was no change of their DjVu file. The change seems to be produced by ia-upload, whose version contains the DjVu images twice:

```
$ djvudump loeuvredumarquis00sadeuoft.djvu  | grep directory
    DIRM [2735]       Document directory (bundled, 354 files 354 pages)
$ djvudump Sade_-_L\'oeuvre_du_marquis_de_Sade\,_1909.djvu  | grep directory
    DIRM [2735]       Document directory (bundled, 354 files 354 pages)
    DIRM [2735]       Document directory (bundled, 354 files 354 pages)
```

**Comment by samwilson** [comment] 2017-02-10 04:19
That IA item already has a DjVu, so I'm not sure why ia-upload would've been modifying it again.

Do you know if this is still happening? Can you help find the root cause? Do we need to fix anything here?

Thanks!

**Comment by samwilson** [comment] 2017-06-26 22:53
I don't think we've seen this crop up again, so I'm closing this and hoping it's resolved (I'm pretty sure it is).

**Closed by samwilson** 2017-06-26 22:53 UTC
Labels: bug
