### ISSUE TITLE
Tool not working for "new" books: No DjVu or PDF file found !

### ISSUE THREAD

**Issue by Aubreymcfato** [wikisource/ia-upload#13] opened 2016-09-29 11:31 UTC
I've tried 2 different books, bot uploaded on IA after they stopped deriving the djvu.
Prospetto biografico delle donne italiane: https://archive.org/details/gri_33125014412924
Come ruinare l'autorità, Tolstoj, 1919: https://archive.org/details/ComeRuinareLAutoritaImage

In both cases, the tool gives me the error "No DjVu or PDF file found !", but the PDF is present.

**Comment by alexbrollo** [comment] 2016-09-29 13:15
To obtain best djvu from present public IA fileset, the best way seems to download _jp2.zip files, to get a djvu with no resizing of converted images, and to inject into resulting djvu the file _djvu.xml.  I found that IA .pdf is very compressed sometimes, and that image quality is far from optimal.

**Comment by Tpt** [comment] 2016-09-30 15:14
I've just fixed a first issue related to the detection of PDF files. See change 7657bfeeedda93afaa7f3becbd09a5db11c98ae1

But now ia-upload run in a Phe converter error. See bug https://github.com/phil-el/phetools/issues/10

**Comment by Tpt** [comment] 2016-10-01 13:24
The conversion no works. But as Phe tools use the PDF the output is very bad: https://commons.wikimedia.org/w/index.php?title=File%3ATolstoy_-_Come_ruinare_l'autorità%2C_1919.djvu&page=1

**Comment by alexbrollo** [comment] 2016-10-01 13:41
This is why I abandoned the simpler road of pdf2djvu .... if pdf is bad,
resulting djvu is bad.

This is the result, using _jp2.zip and _djvu.xml files:

https://commons.wikimedia.org/w/index.php?title=File%
3ATolstoj_-_Come_ruinare_l'autorità.djvu&page=1

(I uploaded the file with a subly different title, just to allow a simpler
comparison)


Alex



2016-10-01 15:24 GMT+02:00 Thomas Tanon <notifications@github.com>:

**Comment by samwilson** [comment] 2017-02-01 06:00
@Aubreymcfato I used your IA item above as an test on the new feature in the tool (#14) and it made this: https://commons.wikimedia.org/wiki/File:Prospetto_biografico_delle_donne_italiane_rinomate_in_letteratura_dal_secolo_decimoquarto_dino_a%27_giorni_nostri.djvu

Is that okay quality?

(I guess it might be a dupe of one you've already uploaded, so we should remember to delete this one.)

**Comment by alexbrollo** [comment] 2017-02-01 14:03
IMHO: excellent.

Alex

2017-02-01 7:00 GMT+01:00 Sam Wilson <notifications@github.com>:

**Closed** 2017-02-09 03:04 UTC
Labels: bug
